services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: comandeiro-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongo:27017/comandeiro
    depends_on:
      mongo:
        condition: service_healthy
    restart: always
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
